### ISSUE TITLE
Planned Event BUG: "Page not found" as regular visitor

### ISSUE THREAD

**Issue by HitomiTenshi** [ThemeBoy/SportsPress#165]
I just created the demo and another extra event to see if the bug just happened on the demo events, turns out it happens always on a planned event.

I can see a planned event as a logged in user (e. g. admin user). But once I log out to see the page as a regular visitor and navigate to a planned event, I get an "oops, page not found" error. Going to the same page as admin works and it displays it as a scheduled event.

Events that are in the past (finished) can be seen normally by a visitor.

Is this the intended behavior?

---

SportsPress Version: 2.0.7
WordPress Version: 4.5.2
Webserver Information: nginx/1.10.0
PHP Version: 7.0.7

I tested this with SportsPress being the only plugin enabled, it still doesn't find the page as a regular visitor.

**Comment by ttss82** [comment]
I have the same problem. Have you found the solution yet?

SportsPress Version: 2.1.1

**Comment by brianmiyaji** [comment]
@HitomiTenshi @ttss82 This is usually a permalinks limitation with WordPress. Scheduled (future) posts are blocked when the permalink structure is set to "Default".

Any other setting, for example "Day and name" should work.

**Comment by ttss82** [comment]
Hello brianmiyaji,

Thank's for your quick response. I have set Permalink Settings to Numeric and problem still remains. But this only happens if I have multiple FUTURE events in calendar. So clicking on the calendar with multiple FUTURE events takes me to the new page (url: http://nkbritof.si/archives/date/2016/09/17?post_type=sp_event) where the links to specific events are displayed. When I click on any of this links I got "Page not found" message (example url: http://nkbritof.si/archives/date/2016/09/17?post_type=sp_event).

Any help is appreciated,
Tomaž
