### ISSUE TITLE
Team manager role has extended capabilities

### ISSUE THREAD

**Issue by MounirHamani** [ThemeBoy/SportsPress#168]
Hi Brian,
I used a test user to test the team manager role and found that although they had the following notice at the top of the player edit page:

> You are not allowed to edit this item.

They could still edit the players profiles and have those edits live on the website even if those plauers aren't part of their team. Actually, the test user didn't have any team assigned to him.

Also, the user could edit any match even if it wasn't his team that was playing. Here again, he didn't even have a team.
And when editing a match a team manager could select any player even if not part of his team...

**Comment by brianmiyaji** [comment]
@MounirHamani Thanks for letting me know! The bug here is that the notice is being displayed at the top of the page. Team managers should be able to edit players from any team, unless they have a team assigned to them. If no teams are assigned, they have full access.

I'll go ahead and fix the issue with the notice so that it only shows when the user has a team assigned to them, but is not the team that they are viewing.

**Comment by MounirHamani** [comment]
Hi @brianmiyaji ,
Thanks for the prompt reply.

You were right, the team manager is limited to his club only when he creates one. But then again there is the same notice if he tries to edit his club or a player of his team (the notice is there but the edits go through anyway). The other issue which is still present after creating the club is that the team manager still has access to all players and not just to the one or ones he created or that are assigned to his club.

**Comment by brianmiyaji** [comment]
@MounirHamani Thanks for the additional info. We'll be releasing a fix soon which addresses these issues so that:

- Team managers assigned to a specific team can only edit players, staff, and events related to the team assigned to them.
- Team managers with no team assignment can edit all players, staff, and events.
- Notices will be displayed only when the user doesn't have permission to edit.
- Players, staff, and events unrelated to the user's team will not be displayed in the admin.

Since this is a Pro feature (Team Access module), I'll close this ticket and will address it in the next update.

**Comment by MounirHamani** [comment]
Thanks,
The client, I am working with, does have the pro version.
I was going to contribute a fix but since this isn't part of this codebase I will let that to you. Being it a Pro feature explains why you set those capabilities to "true" in here.

Thanks again for your prompt reply.
Have a nice day,
Cordially, Mounir.

**Comment by MounirHamani** [comment]
One last thing @brianmiyaji ,
The team manager can create Player Lists while he shouldn't be able to do so.
You should fix this along with the other issues since it's related.

Just to confirm for you, we do have the Access Module activated (checked).

**Comment by krevaestudio** [comment]
Is there a fix for this? I have the exact same issue, although it's been 6 years from this thread, I can't find a solution. All Team Managers have access to edit any player of any team even with Team Access enabled and configured
