### ISSUE TITLE
Career total

### ISSUE THREAD

**Issue by yoye** [ThemeBoy/SportsPress#206]
Equations not working in career stats. For a baseball player, a common batting stat is the Average, it's just the number of hit divide by the number of at-bat. This a default equation in baseball addon and it works great for a year calculation but for a career total, all rows are added which has no sense. It must always keep the formula.

**Comment by Luckycharm1978** [comment]
I definitely agree with you, I'm using the sportspress plugin for my baseball website and its great, all the features really make the plugin a great package for my teams site.  However, when it comes to the career total AVG, OBP, ERA, it just adds up all the seasons, but doesn't do the proper calculation.  Hope they assign someone to this issue soon, Ive been using the plugin for about 2 years now and have been asking for this issue to be fixed since the beginning.

**Comment by brianmiyaji** [comment]
@yoye @Luckycharm1978 

Thanks for your feedback on this issue. I've been assigned to add a totals definition to player stats to enable totals- or average-based career totals.

Aiming to include this in the next update.

**Comment by brianmiyaji** [comment]
Fixed via cac416fdbc6da324cb0c7b03cbc8744465072fbb
